# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20160815_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='prenom',
            field=models.CharField(max_length=100, verbose_name='prenom'),
        ),
    ]
