# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20160815_1337'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='groupe',
            table='contacts_groups',
        ),
    ]
