# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20160815_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupe',
            name='nom',
        ),
        migrations.AddField(
            model_name='groupe',
            name='nom_groupe',
            field=models.CharField(default=0, max_length=200, verbose_name='Nom'),
            preserve_default=False,
        ),
    ]
