# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20160815_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='pays',
            new_name='pays_number',
        ),
    ]
