# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 12:17
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_Erreur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_erreur', models.CharField(max_length=50, verbose_name='Message')),
                ('status', models.CharField(max_length=5, verbose_name='Status')),
                ('numero', models.CharField(max_length=15, verbose_name='Numero Téléphone')),
                ('code_message', models.CharField(max_length=10, verbose_name='Code Message')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('msg_erreur_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message_Multi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '7xxxxxxxx'. Up to 9 digits allowed.", regex='^(7\\d{8},?)+$')], verbose_name='Numero Téléphone')),
                ('sender', models.CharField(max_length=15, verbose_name='From')),
                ('message', models.TextField(max_length=160, verbose_name='Message')),
                ('status_message', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('code', models.CharField(max_length=7, verbose_name='Code')),
            ],
        ),
        migrations.CreateModel(
            name='Pays_Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pays', models.CharField(max_length=25, verbose_name='Pays')),
                ('indicatif_pays', models.CharField(max_length=4, verbose_name='Indicatif')),
                ('prix_sms', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reseau', models.CharField(max_length=10, verbose_name='Reseau')),
                ('cout_message', models.CharField(max_length=5, verbose_name='Prix_message')),
                ('message_id', models.CharField(max_length=15, verbose_name='Message_id')),
                ('numero_telephone', models.CharField(max_length=15, verbose_name='Numero de Téléphone')),
                ('status_reponse', models.CharField(max_length=10, verbose_name='Status')),
                ('credit_restant', models.CharField(max_length=5, verbose_name='Crédit restant')),
                ('compteur_message', models.CharField(max_length=10, verbose_name='Compteur Message')),
                ('code_message', models.CharField(max_length=10, verbose_name='Code Message')),
                ('date_reponse', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('reponse_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message_multi',
            name='pays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sva.Pays_Destination'),
        ),
        migrations.AddField(
            model_name='message_multi',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
