# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sva', '0002_auto_20160609_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_erreur',
            name='msg_erreur_utilisateur_id',
            field=models.IntegerField(default=0, verbose_name='ID Utilisateur'),
        ),
        migrations.AlterField(
            model_name='message_multi',
            name='utilisateur_id',
            field=models.IntegerField(default=0, verbose_name='ID Utilisateur'),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='reponse_utilisateur_id',
            field=models.IntegerField(default=0, verbose_name='ID Utilisateur'),
        ),
    ]
