# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 17:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sva', '0003_auto_20160609_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message_multi',
            name='utilisateur_id',
        ),
        migrations.AlterField(
            model_name='message_multi',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
