# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sva', '0004_auto_20160609_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='message_erreur',
            name='msg_erreur_utilisateur_id',
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='reponse_utilisateur_id',
        ),
        migrations.AlterField(
            model_name='message_erreur',
            name='msg_erreur_utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='reponse_utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
