# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 14:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='numero_telephone',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '7xxxxxxxx'. Up to 9 digits allowed.", regex='^7\\d{8}$')]),
        ),
    ]
